# Generated by Django 3.1 on 2021-01-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bender', '0002_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='name',
            field=models.CharField(default='bender', max_length=244),
        ),
    ]
